### ISSUE TITLE
As an external user, I can login and view my profile information

### ISSUE THREAD

**Issue by acoard-aot** [bcgov/nr-epd-digital-services#111]
**As a** *External User (CSAP, QP, or general public)* **I want** *to be able and login and update my profile information* **So That** *my account details and applications can persist between sessions.*

**Additional Context**
- Request made for BCeID Basic + Biz, and BC Services Card from SSO team
- Includes frontend work and creating routes, and login with standard Keycloak IDP login page.
- Includes backend work, creating all the routes
- The login page should include custom branding and styling similar to TAFT, but we can use default designs in meanwhile so this task is not blocked by needing designs. Example: https://web-test-taft.apps.silver.devops.gov.bc.ca/
- Setting up Biz BCeID account may require custom requests, but we can do test development with normal BCeID, just minor dev work at most between the two.

**Acceptance Criteria**
- [x] Given the user is not logged in, When they visit the application, Then they should be able to login via BCeID, Biz BCeID
- [x] Given the user has never logged in before, When they login for the very first time to create an account, Then the user should be taken to a "user profile" screen.
- [x] Given the user has logged in before, When they login for subsequent times, Then they should be taken to a dashboard view.

**Sub-tasks**
- [ ] Need to setup Biz BCeID process, may require custom submission on-boarding

**Designs**
https://www.figma.com/file/gzF7SL5xpYr5PIY4FyE1TF/Internal-SITE%2FCATS?node-id=8%3A4894&t=u6BHt4AmuGSd3eIf-0

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [x] Documentation and/or scientific documentation exists and can be found
- [x] Peer Reviewed by 2 people on the team
- [x] Manual testing of all PRs in Dev
- [x] Merged

**Comment by acoard-aot** [comment]
Estimated only on Basic and Biz BCeID.

**Comment by acoard-aot** [comment]
For the CSAP/QP question, if user selects "Yes", we can ask if they are CSAP or QP (i.e. they must specify which type). Discussed during team standup.

**Comment by acoard-aot** [comment]
Team also needs region list.  Are we getting this from existing db, or do we have a list we can use for now?

**Comment by acoard-aot** [comment]
Team decided for now to use dummy data for Region info, but can fill it out properly before release.  As said before, we might get all regions from #77.

**Comment by acoard-aot** [comment]
Vancouver Island/Coast
Mainland/Southwest
Thompson-Okanagan
Kootenay
Cariboo
North Coast
Nechako
Northeast
