### ISSUE TITLE
User Research/Testing Roadmap

### ISSUE THREAD

**Issue by mariaye-aot** [bcgov/nr-epd-digital-services#140]
**User Research/Testing Roadmap**
Develop a UXR/UT Roadmap for the EPD project. 

**Acceptance Criteria**
- [ ] Draft completed by Mariaye 11/15/22
- [ ] Include plans for internal and external testing
- [ ] Include key research goals, methods and a timeline
- [ ] PO approval

**SME/User Contact**
@hsawyerPO

**Comment by hsawyerPO** [comment]
Thanks @mariaye-aot - appreciate the pivot to a full UXR/UT roadmap. we an ensure Kevin supports this work as well.
